# numpy
* numerical python or numeric python
* numpy is a programing language that deals with multi -dimensionl 

In [5]:
import numpy as np


In [6]:
print(np.__version__)

1.19.2


In [8]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [9]:
print(np.array([1,2,3,4]))

[1 2 3 4]


In [11]:
print(np.array([1,2,3,4]))

[1 2 3 4]


In [13]:
data=np.array([1,2,3,4])
data

array([1, 2, 3, 4])

In [16]:
data=np.array([1,2,3,4],[5,6,7,8])
data

TypeError: Field elements must be 2- or 3-tuples, got '5'

In [17]:
data=np.array([[1,2,3,4],[5,6,7,8]])
data

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
#mathematical operations
a1=np.array([3,4,5,6])
a2=np.array([5,6,7,8])
a1+a2

array([ 8, 10, 12, 14])

In [19]:
a1=np.array([3,4,5,6])
a2=np.array([5,6,7,8])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1%a2)
print(a1/a2)

[ 8 10 12 14]
[-2 -2 -2 -2]
[15 24 35 48]
[3 4 5 6]
[0.6        0.66666667 0.71428571 0.75      ]


In [27]:
#shape of array
data=np.array([[1,2,3,4],[5,6,7,9]])
print(np.shape(data))
print(data.dtype)

(2, 4)
int32


In [32]:
data=np.array([[1,2,3,4,],[5,6,7,9],[1.3,1.5,5.4,6.4]])
print(np.shape(data))
print(data.dtype)

(3, 4)
float64


In [39]:
#numpy zeros and ones
#numpy zero
np.zeros
np.zeros((3,2),dtype=str)

array([['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

In [40]:
np.zeros
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [41]:
data=np.array([[1,2,3,4],[5,6,7,9]])
data.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 9]])

In [43]:
data=np.array([[1,2,3,4],[5,6,7,9]])
data.flatten()

array([1, 2, 3, 4, 5, 6, 7, 9])

In [46]:
#numpy hstack(data apended horizontally)
a1=[1,2,3,4]
a2=[5,6,7,8]
np.hstack(a1+a2)


array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
a1=[1,2,3,4]
a2=[5,6,7,8]
print(np.vstack(a1+a2))


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [50]:
a1=[1,2,3,4]
a2=[5,6,7,8]
np.hstack((a1,a2))#(())must be used


array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
a1=[1,2,3,4]
a2=[5,6,7,8]
np.hstack(a1)


array([1, 2, 3, 4])

In [56]:
a1=[1,2,3,4]
a2=[5,6,7,8]
print(np.vstack(a1))


[[1]
 [2]
 [3]
 [4]]


In [58]:
print(data)
data.mean()

[[1 2 3 4]
 [5 6 7 9]]


4.625

In [59]:
data=np.array([[1,2,3,4],[5,6,7,9]])
data.std()#standard deviation

2.496873044429772

In [68]:
data=np.array([[1,2,3,4],[5,6,7,9]])
np.median(data)#median not suported in numpy

4.5

In [75]:
data=np.array([[1,2,3,4],[5,6,7,9]])
np.mean(data)

4.625

In [81]:
np.mod(6,5)

1

In [67]:
#random numbers in numpy
data=np.array([[1,2,3,4],[5,6,7,9]])
a={1,2,3,3}
a.random(data)

AttributeError: 'set' object has no attribute 'random'

In [83]:
np.random.rand(4,5)

array([[0.683069  , 0.66120683, 0.89229703, 0.2810799 , 0.83283561],
       [0.21063637, 0.00986668, 0.56715505, 0.7032668 , 0.34893952],
       [0.89103281, 0.60157384, 0.12777535, 0.84650017, 0.19698222],
       [0.9468315 , 0.54584302, 0.53843302, 0.8390338 , 0.91776972]])

In [84]:
np.random.rand(1,50)

array([[0.80496676, 0.94455663, 0.12155201, 0.09908943, 0.5402861 ,
        0.50686451, 0.39564669, 0.47273471, 0.71616159, 0.89401018,
        0.38726479, 0.09918846, 0.16758224, 0.84953098, 0.61528735,
        0.26142454, 0.65818765, 0.45859623, 0.40415431, 0.28189444,
        0.05036073, 0.738092  , 0.25912513, 0.79073891, 0.48645563,
        0.12939851, 0.21667867, 0.80750714, 0.83960813, 0.10826575,
        0.13768605, 0.60198137, 0.54557558, 0.66863363, 0.24605218,
        0.98496037, 0.01964532, 0.29888351, 0.51234212, 0.36235393,
        0.80390704, 0.8231951 , 0.25800894, 0.90106521, 0.095669  ,
        0.80886953, 0.61841584, 0.14627015, 0.8908604 , 0.70353571]])

In [86]:
np.random.randint(5,size=10)

array([4, 0, 3, 3, 2, 2, 0, 0, 1, 4])

In [87]:
#np.random.normal(loc(mean),scale())
np.random.normal(5,4,10)

array([-2.08162663,  2.42150817,  8.89281534,  2.47879038,  9.41532702,
       -4.58138431,  4.99720453, 11.41802561,  5.75784931,  2.56504922])

In [94]:
data=np.array([1,2,3,4])
data.min()

1

In [95]:
data.max()

4

In [96]:
data.mean()

2.5

In [97]:
data.std()

1.118033988749895

In [103]:
a=np.random.randint(4)
print(a)
b=type(np.random.randint(4))
print(b)
c=np.random.randint((5))
print(c)

1
<class 'int'>
4


In [106]:
#transpose
data=np.array([[1,2,3],[4,5,6],[7,8,9]])
data.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [109]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [1]:
print(a1)
print(a2)
a1.dot(a2)

NameError: name 'a1' is not defined

In [112]:
#power =np.array()
n=np.array([1,2,3,4])
np.array([n,pow(n,3)])

array([[ 1,  2,  3,  4],
       [ 1,  8, 27, 64]])

In [3]:
#repeat
import numpy as np
a=np.repeat([1,2,3,4],5)
a

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4])

In [6]:
a=np.repeat([1],6)
a

array([1, 1, 1, 1, 1, 1])

In [8]:
#arrange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
n=5
fact=1
np.arange(1,6)
fact=fact*np
print(np)



TypeError: unsupported operand type(s) for *: 'int' and 'module'

In [16]:
#factorial
a = np.math.factorial(4)
print(a)

24


In [29]:
n=int(input())
count=0
def is_prime(n):
    if n%2==0 or n==2:
        count=count+1
    return'is_prime'
a = np.arange(0,10)
foo = np.vectorize(is_prime)
pbools = foo(a)
primes = np.extract(pbools, a)
primes

4


UnboundLocalError: local variable 'count' referenced before assignment

In [23]:
#numpy linespace
#syntax-->linespace(start,stop,num=endpoint)
np.linspace(1,5,num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [27]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])